### ISSUE TITLE
Doesn't work on macOS Ventura 13.0

### ISSUE THREAD

**Issue by RaeesBhatti** [jakubroztocil/macos-fn-toggle#12]
Thank you for creating this! It might be exactly what I've been looking for, for a long while. But I doesn't seem to run on macOS 13. I'm assuming it's because they changed the layout of the System Preferences app.
Could you please update or give me patch to make it work on macOS Ventura!

**Comment by zimmermax98** [comment]
I'm getting the error `The action “Run AppleScript” encountered an error: “System Settings got an error: AppleEvent handler failed.`
Is it the same for you?

**Comment by itsabk** [comment]
> I'm getting the error `The action “Run AppleScript” encountered an error: “System Settings got an error: AppleEvent handler failed.` Is it the same for you?

Yes, I'm getting the same error on Ventura 13.1

**Comment by gabrielcipriano** [comment]
hey , I managed to make fn-toggle run on macos Ventura. The interface had a substantial change, so the script got a bit more complex.. I'm not used to write AppleScript, so suggestions are wellcomed 

please check the PR out here: #13 

to try it yourself, please clone the fork: 
`https://github.com/gabrielcipriano/macos-fn-toggle-ventura`

the steps are pretty much the same:
`make install`

go to `System Settings` > `Privacy & Security` > `Accessibility` 

allow `fn-toggle`

**Comment by bryce-natter** [comment]
> hey , I managed to make fn-toggle run on macos Ventura. The interface had a substantial change, so the script got a bit more complex.. I'm not used to write AppleScript, so suggestions are wellcomed
> 
> please check the PR out here: #13
> 
> to try it yourself, please clone the fork: https://github.com/gabrielcipriano/macos-fn-toggle-ventura the steps are pretty much the same: `make install`
> 
> go to `System Settings` > `Privacy & Security` > `Accessibility`
> 
> allow `fn-toggle`

Just tried your fork on 13.2.1 and got the following error: 
`The action “Run AppleScript” encountered an error: “System Settings got an error: AppleEvent handler failed.”`

**Comment by gabrielcipriano** [comment]
> > hey , I managed to make fn-toggle run on macos Ventura. The interface had a substantial change, so the script got a bit more complex.. I'm not used to write AppleScript, so suggestions are wellcomed
> > please check the PR out here: #13
> > to try it yourself, please clone the fork: https://github.com/gabrielcipriano/macos-fn-toggle-ventura the steps are pretty much the same: `make install`
> > go to `System Settings` > `Privacy & Security` > `Accessibility`
> > allow `fn-toggle`
> 
> Just tried your fork on 13.2.1 and got the following error: `The action “Run AppleScript” encountered an error: “System Settings got an error: AppleEvent handler failed.”`

I tried only on the latest version: 13.3.1 (a)

**Comment by itsabk** [comment]
> hey , I managed to make fn-toggle run on macos Ventura. The interface had a substantial change, so the script got a bit more complex.. I'm not used to write AppleScript, so suggestions are wellcomed
> 
> please check the PR out here: #13
> 
> to try it yourself, please clone the fork: https://github.com/gabrielcipriano/macos-fn-toggle-ventura the steps are pretty much the same: `make install`
> 
> go to `System Settings` > `Privacy & Security` > `Accessibility`
> 
> allow `fn-toggle`

Works perfectly on 13.3.1 (a). Thanks!

**Comment by jkbrzt** [comment]
@gabrielcipriano’s fix is now in `master`, thanks!
