### ISSUE TITLE
not working in macOS Sierra

### ISSUE THREAD

**Issue by kevindashgit** [jakubroztocil/macos-fn-toggle#7]
OSX v10.12.6

Probably this is assumed w/ the fancy new touch bar and the complexity it introduces - but a `fn` key toggle would be AWESOME for my workflow! 

Any known workarounds?

**Comment by biocross** [comment]
It seems to be working for me. What exactly is the issue you're facing? It's even working on High Sierra for me.

**Comment by kevindashgit** [comment]
When I attempt to run it I get the error (in a dialog window) `The action "Run AppleScript" encountered an error.`

**Comment by biocross** [comment]
Oh I got this too when I upgraded to Sierra. Just delete the current binary you have, re-download and follow the installation steps again, it'll start working.

**Comment by kevindashgit** [comment]
hmmm - I tried this but no luck.

```
git pull && make clean && make install && ./fn-toggle.app/Contents/MacOS/Application\ Stub
```

yields both the error dialog mentioned above along w/ the following output in stdout:
```
2017-10-02 13:02:42.974 Application Stub[78836:2812651] Cache file at /System/Library/Caches/com.apple.automator.actionCache-system-readonly.plist is not valid: System Languages have changed.
2017-10-02 13:02:42.974 Application Stub[78836:2812651] Failed to use read-only system cache from installer at /System/Library/Caches/com.apple.automator.actionCache-system-readonly.plist.
```

**Comment by kevindashgit** [comment]
Actually . - now that I look more closely at the automator script - the Keyboard pane of System Preferences no longer contains a checkbox that allows default usage of F1, F2, etc Keys - so default selecting the first checkbox wouldn't do the trick. In fact, it *should* have checked `Adjust keyboard brightness in low light` but for whatever reason this doesn't happen.

**Comment by kevindashgit** [comment]
In the end - I found this to be a solution that better suited my needs: https://www.imore.com/how-make-function-keys-default-touch-bar-display

As its application specific and not system wide - which is super ideal IMO.

**Comment by sthodup1** [comment]
Here's a fix:

**Comment by sthodup1** [comment]
Also make sure to give fn-toggle accessibility access

**Comment by jkbrzt** [comment]
`master` updated to work with Ventura
